FROM rust:1.86.0-slim-bullseye AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM rust:1.86.0-slim-bullseye
COPY --from=builder /app/target/release/mafia_server /
COPY --from=builder /app/resources /resources
EXPOSE 80
RUN chmod +x mafia_server
CMD ["./mafia_server"]

# docker build -f dockerfile -t midnightmachinations-server .
# docker run -p 80:80  midnightmachinations-server