FROM rust:1.86.0 as builder
WORKDIR /app
COPY . /app
RUN cargo build --release

FROM debian:bullseye-slim
COPY --from=builder /target/release/mafia_server /
COPY --from=builder /resources /
EXPOSE 80
RUN chmod +x mafia_server
CMD ["./mafia_server"]