name: CI/CD

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code from prod branch
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: prod

      # 2. Log in to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build & push server image
      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/midnightmachinations-server:latest
          build-args: |
            WS_ADDRESS=0.0.0.0:80

      # 4. Build & push client image
      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: ./client/dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/midnightmachinations-client:latest
          build-args: |
            REACT_APP_WS_ADDRESS=wss://wss.midnightmachinations.net

      # 5. Configure SSH for deployment
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts || true

      # 6. Deploy to Server
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=yes -p ${{ secrets.SSH_PORT }} \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Pull latest images
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/midnightmachinations-server:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/midnightmachinations-client:latest

            # Restart server container
            docker stop mm-server || true
            docker rm mm-server || true
            docker run -d --restart always \
              --name mm-server -p 80:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/midnightmachinations-server:latest

            # Restart client container
            docker stop mm-client || true
            docker rm mm-client || true
            docker run -d --restart always \
              --name mm-client -p 3000:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/midnightmachinations-client:latest
          EOF
