name: Rust

on:
  push:
    branches: [ "main", "prod" ]
  pull_request:
    branches: [ "main", "prod" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cd server
    - name: Build
      run: cd server
        cargo build --verbose
    - name: Run tests
      run: cd server
        cargo test --verbose
